coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: 85%
        threshold: 0.5%
    patch:
      default:
        target: 85%
        threshold: 5%

ignore:
  - migrations
  - tests

comment:
  layout: "condensed_header, diff, files"
  behavior: default
  require_changes: true
