[tools]
"aqua:evilmartians/lefthook" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jessfraz/dockfmt" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:zricethezav/gitleaks" = "latest"
go = "1.22"
"go:github.com/air-verse/air" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"npm:markdownlint-cli2" = "latest"
"pipx:gitfluff" = "latest"
"pipx:yamllint" = "latest"
prettier = "latest"
shfmt = "latest"
task = "3"
